module.exports = {
    folder_app   	    : 'app'
    , folder_configs    : 'configs'
    , folder_helpers    : 'helpers'
    , folder_routes	    : 'routes'
    , folder_schemas    : 'schemas'
    , folder_models     : 'models'
    , folder_validators : 'validators'
    , folder_middleware   : 'middleware'
    , folder_views		: 'views'
    , folder_module_admin : 'admin'
    , folder_module_blog : 'blog'
    , folder_module_chat  : 'chat'
    , folder_public		: 'public'
    , folder_uploads    : 'uploads'
}