module.exports = {
    CHANGE_STATUS_SUCCSESS: 'Cập nhật status thành công!'
    , CHANGE_SPECIAL_SUCCESS: 'Cập nhật special thành công'
    , CHANGE_STATUS_MULTI_SUCCSESS: 'Có %d phần tử được cập nhật status thành công!'
    , CHANGE_GROUP_ACP_SUCCSESS: 'Cập nhật Group ACP thành công!'
    , CHANGE_ORDERING_SUCCESS: 'Cập nhật ordering thành công'
    , DELETE_SUCCESS: 'Xóa phần tử thành công'
    , DELETE_MULTI_SUCCESS: 'Có %d phần tử được xóa thành công'
    , ADD_SUCCESS: 'Thêm mới phần tử thành công'
    , EDIT_SUCCESS: 'Cập nhật thông tin phần tử thành công'
    , ERROR_NAME: 'Chiều dài từ %d đến %d ký tự'
    , ERROR_ORDERING: 'Phải là số nguyên lớn hơn %d và bé hơn %d'
    , ERROR_STATUS: 'Phải chọn giá trị status'
    , ERROR_GROUP: 'Phải chọn giá trị khác rỗng'
    , ERROR_GROUPACP: 'Phải chọn giá trị status'
    , ERROR_FILE_REQUIRE: 'Vui lòng chọn file upload'
    , ERROR_FILE_LIMIT: 'Kích thước file không phù hợp'
    , ERROR_FILE_EXTENSION: 'Phần mở rộng file không hợp lệ'
    , ERROR_LOGIN_USERNAME_NOTEXIST: 'Username không tồn tại'
    , ERROR_LOGIN_PASSWORD_INCORRECT: 'Password không chính xác'
    , ERROR_LOGIN: 'Thông tin đăng nhập không chính xác'

    , ERROR_MSG_CHAT_TOO_SHORT: 'Chiều dài tin nhắn quá ngắn'
}